```{r}
link="https://github.com/Vis-Analytics-FinalProj/RawData/raw/main/Seattle_Pet_Licenses%20CLEANED.xlsx"
library(rio)
mydata=import(link)
```

```{r}
library(dplyr)
library(waffle)
library(tidyverse)
library(ggplot2)
library(scales)
library(hrbrthemes)
library(lubridate)
```


```{r}
str(mydata,width = 150,strict.width='cut')
```

```{r}
mydata$LicenseIssueDate <- mdy(mydata$`License Issue Date`)
```

NEW! - create data frame

```{r}
# key change
mydata$LicenseIssueDate=floor_date(mydata$LicenseIssueDate,"month")
```

```{r}
dogdata <- mydata[, -c(1, 3:4)] 
```

```{r}
head(dogdata)
```

```{r}
A= as.data.frame(dogdata)
```

```{r}
dogdate <- A[ which(A$Species=='Dog'), ]
```

```{r}
head(dogdate)
```

```{r}
DFDog=as.data.frame(table(dogdate$LicenseIssueDate), stringsAsFactors =FALSE)
names(DFDog)=c("Time","Count")
DFDog
```

```{r}
#key change!
DFDog$Time=as.Date(DFDog$Time)
head(DFDog, 25)
```




```{r}
DFDog_sub=DFDog[DFDog$Time>=as.Date('2019-02-01'),]
baseD=ggplot(data=DFDog_sub, aes(x=Time,y=Count))
bar1=baseD+geom_bar(stat = 'identity', color="steelblue", fill = "steelblue" )
bar1
```

```{r}
bar2=bar1 + scale_x_date(breaks = date_breaks("months"),
  labels = date_format("%b-%y"))  
bar3=bar2 + theme(axis.text.x = element_text(angle = -90, vjust = .2)) 
bar3
```

```{r}
bar4=bar3 + geom_text(aes(label=Count),
                      angle=-90 ,
                      size=4,
                      hjust = -0.2,
                      vjust = .3,
                      color='white')
bar4
```

```{r}
bar5= bar4 + labs(title = "Dogs Adopted in King Co.",
                                                                           subtitle= "From Jan 2019 - Jan 2021",
                                                                           x="Time", 
                                                                           y="Count",
                                                                           caption = "Source: King County") + theme(plot.subtitle = element_text(hjust = 0.5), 
                      plot.title = element_text(hjust = 0.5),
                      plot.caption = element_text(hjust = 1))
  
bar5
```

```{r}
bar6= bar5 + geom_text(aes(x=as.Date('2020-03-01'), label="WA Lockdown 3/23/'20", y=1000), color="orange", angle=-90, size=3, vjust=.2 ) 

                
bar6
```
```{r}
bar7= bar6 + theme_classic() +  theme(axis.text.x = element_text(angle = -90, vjust = .2)) +labs(title = "Dogs Adopted in King Co.",
                                                                           subtitle= "From Jan 2019 - Jan 2021",
                                                                           x="Time", 
                                                                           y="Count",
                                                                           caption = "Source: King County") + theme(plot.subtitle = element_text(hjust = 0.5), 
                      plot.title = element_text(hjust = 0.5),
                      plot.caption = element_text(hjust = 1))
bar7
```











