```{r}
link="https://github.com/Vis-Analytics-FinalProj/RawData/raw/main/Seattle_Pet_Licenses%20CLEANED.xlsx"

library(rio)
dogdata=import(link)
```

```{r}
## limits Species to just cats
newdata <- dogdata[ which(dogdata$Species=='Dog'
), ]

C = table(newdata$Species, newdata$`ZIP Code`)
D = as.data.frame(C)
names(D)[1] = 'Species'
names(D)[2] = 'ZIP Code'
```

```{r}
## link the ZIP code map
linkMap="https://github.com/Vis-Analytics-FinalProj/Rebecca-Taylor/raw/main/Zipcodes_for_King_County_and_Surrounding_Area___zipcode_area%20(1).json"

library(sf)
WAmap=read_sf(linkMap)

MergedDog=merge(WAmap,
                   D, 
                   by.x='ZIPCODE', by.y='ZIP Code') 
```
```{r}
library(ggplot2)
library(RColorBrewer)

base=ggplot(data=WAmap) + geom_sf(fill='grey95',
                                  color='grey40',
                                  lwd=0.5) + theme_classic()

MapCol= base + geom_sf(data=MergedDog,
                       aes(fill=-Freq),
                       color="grey40",
                       lwd=0.25)+
  scale_color_brewer(palette = "PuRd")
MapCol
```  

```{r}
ZipMap = MapCol + 
  geom_text(x=-122.35, y=47.608013, size=3, color = "black", label="98103") +
  geom_text(x=-122.6, y=47.7, size=3, color = "black", label="98117")+
  geom_text(x=-122.1, y=47.7, size=3, color = "black", label="98115")


## Adding title names
Titles=list(Title="Dog Licenses Issued in King County by ZIP Code - Top Three",
            SubTi="Dec 2015-Jan 2021",
            Sou="Source: King County")

## placing the titles on the graph
plot2= ZipMap + labs(title = Titles$Title,
                    subtitle = Titles$SubTi,
                    caption = Titles$Sou)

plot3 = plot2 + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())


bartext=plot3 + labs(fill = "Count")

Mapfinal = bartext + theme(
  plot.title = element_text(hjust = 0.5),
  plot.subtitle = element_text(hjust = 0.5)
)
Mapfinal
```




